#!/usr/bin/env node

var gaze_run_interrupt = require('gaze-run-interrupt');

gaze_run_interrupt('{src,test}/**/*.ts', [{
    command: 'node_modules/.bin/tsc'
}, {
    command: '../../node_modules/.bin/mocha',
    args: ['--reporter', 'min'],
    cwd: 'dist/js'
}]);
